# Generated by Django 4.2 on 2023-05-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
